version: 2
updates:
  -
    # Maintain repository workflows dependencies
    package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"

  # Group by scope/dir so code owners of different actions groups have different pull requests
  # See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
  -
    # Maintain dependencies for gh-* actions
    package-ecosystem: github-actions
    directories:
      - /gh-*
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for python-app and python-lib
    package-ecosystem: github-actions
    directories:
      - /python-app/**
      - /python-lib/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for pdm actions
    package-ecosystem: github-actions
    directories:
      - /pdm/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for allure actions
    package-ecosystem: github-actions
    directories:
      - /allure/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: ci
      include: scope
  -
    # Maintain dependencies for slack-notification
    package-ecosystem: github-actions
    directory: /slack-notification
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for cascade-merge
    package-ecosystem: github-actions
    directory: /cascade-merge
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for docker-metadata
    package-ecosystem: github-actions
    directory: /docker-metadata
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for documentation/c4
    package-ecosystem: github-actions
    directory: /documentation/c4
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for gemfury actions
    package-ecosystem: github-actions
    directories:
      - /gemfury/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for nexus actions
    package-ecosystem: github-actions
    directories:
      - /nexus/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for redocly actions
    package-ecosystem: github-actions
    directories:
      - /redocly/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for helm actions
    package-ecosystem: github-actions
    directories:
      - /helm/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for scala actions
    package-ecosystem: github-actions
    directories:
      - /scala/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
  -
    # Maintain dependencies for slack actions
    package-ecosystem: github-actions
    directories:
      - /slack/**
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "ci"
      include: "scope"
